class ContractQuantificationPlanModel {
  String? id;
  String? house;
  String? side;
  String? houseLogo;
  String? nickname;
  String? accountType;
  String? contract;
  int? leverage;
  int? rounds;
  int? execWay;
  int? times;
  int? ordersNum;
  double? marginRate;
  int? status;
  int? held;
  double? avgCost;
  double? exForcePrice;
  double? notCreditedProfit;
  int? usedAssets;
  double? addPrice;
  double? addSize;
  String? createTime;
  int? execTime;
  double? yield;
  String? currency;
  double? yieldRate;
  num? winRate;
  double? retracementRate;
  String? accountRights;
  double? average;
  double? tpTriggerPrice;
  String? targetStrategyId;
  String? contractCn;
  ContractQuantificationPlanModel.fromJson(Map json) {
    id = json['id'];
    house = json['house'];
    side = json['side'];
    contractCn = json['contractCn'];
    houseLogo = json['houseLogo'];
    nickname = json['nickname'];
    accountType = json['accountType'];
    contract = json['contract'];
    leverage = json['leverage'];
    usedAssets = json['usedAssets'];
    addPrice = json['addPrice'];
    addSize = json['addSize'];
    createTime = json['createTime'];
    execTime = json['execTime'];
    yield = json['yield'];
    currency = json['currency'];
    yieldRate = json['yieldRate'];
    winRate = json['winRate'];
    retracementRate = json['retracementRate'];
    accountRights = json['accountRights'];
    average = json['average'];
    tpTriggerPrice = json['tpTriggerPrice'];
    targetStrategyId = json['targetStrategyId'];
  }
}
